### ISSUE TITLE
Use of exit language construct is discouraged.

### ISSUE THREAD

**Issue by lucasburlingham** [XENONMC-DEV/XFORUM#5]
#### Occurred on:
+ **Commit**:  f9468c45233c965a8f05234dca0f7b0cdc8cb3f6
+ **File**:    [db_conn.php](https://github.com/XENONMC-DEV/XENFORUMS/blob/f9468c45233c965a8f05234dca0f7b0cdc8cb3f6/db_conn.php)
+ **LineNum**: [22](https://github.com/XENONMC-DEV/XENFORUMS/blob/f9468c45233c965a8f05234dca0f7b0cdc8cb3f6/db_conn.php#L22)
+ **Code**:    `exit();`

    
#### Currently on:
+ **Commit**:  e6caa2015cb800fa15f65c2a188c6a363f30f813
+ **File**:    [db_conn.php](https://github.com/XENONMC-DEV/XENFORUMS/blob/e6caa2015cb800fa15f65c2a188c6a363f30f813/db_conn.php)
+ **LineNum**: [22](https://github.com/XENONMC-DEV/XENFORUMS/blob/e6caa2015cb800fa15f65c2a188c6a363f30f813/db_conn.php#L22)
    

Does this  need to be fixed? I have seen this somewhere else, and it merits some attention

**Comment by XfaonXE** [comment]
yes, change printf("error"); exit(); -- to -> die("error");
